/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutChar91indexChar93RouteImport } from './routes/_layout.[index]'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutWarfarinRouteImport } from './routes/_layout.warfarin'
import { Route as LayoutTreatmentRouteImport } from './routes/_layout.treatment'
import { Route as LayoutSyncopeTriageRouteImport } from './routes/_layout.syncope-triage'
import { Route as LayoutSyncopeRouteImport } from './routes/_layout.syncope'
import { Route as LayoutScoresRouteImport } from './routes/_layout.scores'
import { Route as LayoutRhythmsRouteImport } from './routes/_layout.rhythms'
import { Route as LayoutMedcalcRouteImport } from './routes/_layout.medcalc'
import { Route as LayoutGoldmanRouteImport } from './routes/_layout.goldman'
import { Route as LayoutAnticoagulationRouteImport } from './routes/_layout.anticoagulation'
import { Route as LayoutAntiarrhythmicsRouteImport } from './routes/_layout.antiarrhythmics'
import { Route as LayoutProtocolIdRouteImport } from './routes/_layout.protocol.$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutChar91indexChar93Route = LayoutChar91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWarfarinRoute = LayoutWarfarinRouteImport.update({
  id: '/warfarin',
  path: '/warfarin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTreatmentRoute = LayoutTreatmentRouteImport.update({
  id: '/treatment',
  path: '/treatment',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSyncopeTriageRoute = LayoutSyncopeTriageRouteImport.update({
  id: '/syncope-triage',
  path: '/syncope-triage',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSyncopeRoute = LayoutSyncopeRouteImport.update({
  id: '/syncope',
  path: '/syncope',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScoresRoute = LayoutScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRhythmsRoute = LayoutRhythmsRouteImport.update({
  id: '/rhythms',
  path: '/rhythms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMedcalcRoute = LayoutMedcalcRouteImport.update({
  id: '/medcalc',
  path: '/medcalc',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGoldmanRoute = LayoutGoldmanRouteImport.update({
  id: '/goldman',
  path: '/goldman',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnticoagulationRoute = LayoutAnticoagulationRouteImport.update({
  id: '/anticoagulation',
  path: '/anticoagulation',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAntiarrhythmicsRoute = LayoutAntiarrhythmicsRouteImport.update({
  id: '/antiarrhythmics',
  path: '/antiarrhythmics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProtocolIdRoute = LayoutProtocolIdRouteImport.update({
  id: '/protocol/$id',
  path: '/protocol/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/antiarrhythmics': typeof LayoutAntiarrhythmicsRoute
  '/anticoagulation': typeof LayoutAnticoagulationRoute
  '/goldman': typeof LayoutGoldmanRoute
  '/index': typeof LayoutChar91indexChar93Route
  '/medcalc': typeof LayoutMedcalcRoute
  '/rhythms': typeof LayoutRhythmsRoute
  '/scores': typeof LayoutScoresRoute
  '/syncope': typeof LayoutSyncopeRoute
  '/syncope-triage': typeof LayoutSyncopeTriageRoute
  '/treatment': typeof LayoutTreatmentRoute
  '/warfarin': typeof LayoutWarfarinRoute
  '/protocol/$id': typeof LayoutProtocolIdRoute
}
export interface FileRoutesByTo {
  '/antiarrhythmics': typeof LayoutAntiarrhythmicsRoute
  '/anticoagulation': typeof LayoutAnticoagulationRoute
  '/goldman': typeof LayoutGoldmanRoute
  '/index': typeof LayoutChar91indexChar93Route
  '/medcalc': typeof LayoutMedcalcRoute
  '/rhythms': typeof LayoutRhythmsRoute
  '/scores': typeof LayoutScoresRoute
  '/syncope': typeof LayoutSyncopeRoute
  '/syncope-triage': typeof LayoutSyncopeTriageRoute
  '/treatment': typeof LayoutTreatmentRoute
  '/warfarin': typeof LayoutWarfarinRoute
  '/': typeof LayoutIndexRoute
  '/protocol/$id': typeof LayoutProtocolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/antiarrhythmics': typeof LayoutAntiarrhythmicsRoute
  '/_layout/anticoagulation': typeof LayoutAnticoagulationRoute
  '/_layout/goldman': typeof LayoutGoldmanRoute
  '/_layout/index': typeof LayoutChar91indexChar93Route
  '/_layout/medcalc': typeof LayoutMedcalcRoute
  '/_layout/rhythms': typeof LayoutRhythmsRoute
  '/_layout/scores': typeof LayoutScoresRoute
  '/_layout/syncope': typeof LayoutSyncopeRoute
  '/_layout/syncope-triage': typeof LayoutSyncopeTriageRoute
  '/_layout/treatment': typeof LayoutTreatmentRoute
  '/_layout/warfarin': typeof LayoutWarfarinRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/protocol/$id': typeof LayoutProtocolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antiarrhythmics'
    | '/anticoagulation'
    | '/goldman'
    | '/index'
    | '/medcalc'
    | '/rhythms'
    | '/scores'
    | '/syncope'
    | '/syncope-triage'
    | '/treatment'
    | '/warfarin'
    | '/protocol/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/antiarrhythmics'
    | '/anticoagulation'
    | '/goldman'
    | '/index'
    | '/medcalc'
    | '/rhythms'
    | '/scores'
    | '/syncope'
    | '/syncope-triage'
    | '/treatment'
    | '/warfarin'
    | '/'
    | '/protocol/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/antiarrhythmics'
    | '/_layout/anticoagulation'
    | '/_layout/goldman'
    | '/_layout/index'
    | '/_layout/medcalc'
    | '/_layout/rhythms'
    | '/_layout/scores'
    | '/_layout/syncope'
    | '/_layout/syncope-triage'
    | '/_layout/treatment'
    | '/_layout/warfarin'
    | '/_layout/'
    | '/_layout/protocol/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/index': {
      id: '/_layout/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof LayoutChar91indexChar93RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/warfarin': {
      id: '/_layout/warfarin'
      path: '/warfarin'
      fullPath: '/warfarin'
      preLoaderRoute: typeof LayoutWarfarinRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/treatment': {
      id: '/_layout/treatment'
      path: '/treatment'
      fullPath: '/treatment'
      preLoaderRoute: typeof LayoutTreatmentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/syncope-triage': {
      id: '/_layout/syncope-triage'
      path: '/syncope-triage'
      fullPath: '/syncope-triage'
      preLoaderRoute: typeof LayoutSyncopeTriageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/syncope': {
      id: '/_layout/syncope'
      path: '/syncope'
      fullPath: '/syncope'
      preLoaderRoute: typeof LayoutSyncopeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scores': {
      id: '/_layout/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof LayoutScoresRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rhythms': {
      id: '/_layout/rhythms'
      path: '/rhythms'
      fullPath: '/rhythms'
      preLoaderRoute: typeof LayoutRhythmsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/medcalc': {
      id: '/_layout/medcalc'
      path: '/medcalc'
      fullPath: '/medcalc'
      preLoaderRoute: typeof LayoutMedcalcRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/goldman': {
      id: '/_layout/goldman'
      path: '/goldman'
      fullPath: '/goldman'
      preLoaderRoute: typeof LayoutGoldmanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/anticoagulation': {
      id: '/_layout/anticoagulation'
      path: '/anticoagulation'
      fullPath: '/anticoagulation'
      preLoaderRoute: typeof LayoutAnticoagulationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/antiarrhythmics': {
      id: '/_layout/antiarrhythmics'
      path: '/antiarrhythmics'
      fullPath: '/antiarrhythmics'
      preLoaderRoute: typeof LayoutAntiarrhythmicsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/protocol/$id': {
      id: '/_layout/protocol/$id'
      path: '/protocol/$id'
      fullPath: '/protocol/$id'
      preLoaderRoute: typeof LayoutProtocolIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAntiarrhythmicsRoute: typeof LayoutAntiarrhythmicsRoute
  LayoutAnticoagulationRoute: typeof LayoutAnticoagulationRoute
  LayoutGoldmanRoute: typeof LayoutGoldmanRoute
  LayoutChar91indexChar93Route: typeof LayoutChar91indexChar93Route
  LayoutMedcalcRoute: typeof LayoutMedcalcRoute
  LayoutRhythmsRoute: typeof LayoutRhythmsRoute
  LayoutScoresRoute: typeof LayoutScoresRoute
  LayoutSyncopeRoute: typeof LayoutSyncopeRoute
  LayoutSyncopeTriageRoute: typeof LayoutSyncopeTriageRoute
  LayoutTreatmentRoute: typeof LayoutTreatmentRoute
  LayoutWarfarinRoute: typeof LayoutWarfarinRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProtocolIdRoute: typeof LayoutProtocolIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAntiarrhythmicsRoute: LayoutAntiarrhythmicsRoute,
  LayoutAnticoagulationRoute: LayoutAnticoagulationRoute,
  LayoutGoldmanRoute: LayoutGoldmanRoute,
  LayoutChar91indexChar93Route: LayoutChar91indexChar93Route,
  LayoutMedcalcRoute: LayoutMedcalcRoute,
  LayoutRhythmsRoute: LayoutRhythmsRoute,
  LayoutScoresRoute: LayoutScoresRoute,
  LayoutSyncopeRoute: LayoutSyncopeRoute,
  LayoutSyncopeTriageRoute: LayoutSyncopeTriageRoute,
  LayoutTreatmentRoute: LayoutTreatmentRoute,
  LayoutWarfarinRoute: LayoutWarfarinRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProtocolIdRoute: LayoutProtocolIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
