/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutRhythmsRouteImport } from './routes/_layout.rhythms'
import { Route as LayoutProtocolIdRouteImport } from './routes/_layout.protocol.$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRhythmsRoute = LayoutRhythmsRouteImport.update({
  id: '/rhythms',
  path: '/rhythms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProtocolIdRoute = LayoutProtocolIdRouteImport.update({
  id: '/protocol/$id',
  path: '/protocol/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/rhythms': typeof LayoutRhythmsRoute
  '/protocol/$id': typeof LayoutProtocolIdRoute
}
export interface FileRoutesByTo {
  '/rhythms': typeof LayoutRhythmsRoute
  '/': typeof LayoutIndexRoute
  '/protocol/$id': typeof LayoutProtocolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/rhythms': typeof LayoutRhythmsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/protocol/$id': typeof LayoutProtocolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rhythms' | '/protocol/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/rhythms' | '/' | '/protocol/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/rhythms'
    | '/_layout/'
    | '/_layout/protocol/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rhythms': {
      id: '/_layout/rhythms'
      path: '/rhythms'
      fullPath: '/rhythms'
      preLoaderRoute: typeof LayoutRhythmsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/protocol/$id': {
      id: '/_layout/protocol/$id'
      path: '/protocol/$id'
      fullPath: '/protocol/$id'
      preLoaderRoute: typeof LayoutProtocolIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutRhythmsRoute: typeof LayoutRhythmsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProtocolIdRoute: typeof LayoutProtocolIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutRhythmsRoute: LayoutRhythmsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProtocolIdRoute: LayoutProtocolIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
