/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutChar91indexChar93RouteImport } from './routes/_layout.[index]'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutRhythmsRouteImport } from './routes/_layout.rhythms'
import { Route as LayoutGoldmanRouteImport } from './routes/_layout.goldman'
import { Route as LayoutProtocolIdRouteImport } from './routes/_layout.protocol.$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutChar91indexChar93Route = LayoutChar91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRhythmsRoute = LayoutRhythmsRouteImport.update({
  id: '/rhythms',
  path: '/rhythms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGoldmanRoute = LayoutGoldmanRouteImport.update({
  id: '/goldman',
  path: '/goldman',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProtocolIdRoute = LayoutProtocolIdRouteImport.update({
  id: '/protocol/$id',
  path: '/protocol/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/goldman': typeof LayoutGoldmanRoute
  '/index': typeof LayoutChar91indexChar93Route
  '/rhythms': typeof LayoutRhythmsRoute
  '/protocol/$id': typeof LayoutProtocolIdRoute
}
export interface FileRoutesByTo {
  '/goldman': typeof LayoutGoldmanRoute
  '/index': typeof LayoutChar91indexChar93Route
  '/rhythms': typeof LayoutRhythmsRoute
  '/': typeof LayoutIndexRoute
  '/protocol/$id': typeof LayoutProtocolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/goldman': typeof LayoutGoldmanRoute
  '/_layout/index': typeof LayoutChar91indexChar93Route
  '/_layout/rhythms': typeof LayoutRhythmsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/protocol/$id': typeof LayoutProtocolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/goldman' | '/index' | '/rhythms' | '/protocol/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/goldman' | '/index' | '/rhythms' | '/' | '/protocol/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/goldman'
    | '/_layout/index'
    | '/_layout/rhythms'
    | '/_layout/'
    | '/_layout/protocol/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/index': {
      id: '/_layout/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof LayoutChar91indexChar93RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rhythms': {
      id: '/_layout/rhythms'
      path: '/rhythms'
      fullPath: '/rhythms'
      preLoaderRoute: typeof LayoutRhythmsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/goldman': {
      id: '/_layout/goldman'
      path: '/goldman'
      fullPath: '/goldman'
      preLoaderRoute: typeof LayoutGoldmanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/protocol/$id': {
      id: '/_layout/protocol/$id'
      path: '/protocol/$id'
      fullPath: '/protocol/$id'
      preLoaderRoute: typeof LayoutProtocolIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutGoldmanRoute: typeof LayoutGoldmanRoute
  LayoutChar91indexChar93Route: typeof LayoutChar91indexChar93Route
  LayoutRhythmsRoute: typeof LayoutRhythmsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProtocolIdRoute: typeof LayoutProtocolIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutGoldmanRoute: LayoutGoldmanRoute,
  LayoutChar91indexChar93Route: LayoutChar91indexChar93Route,
  LayoutRhythmsRoute: LayoutRhythmsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProtocolIdRoute: LayoutProtocolIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
